### Import libraries

In [41]:
import os
import numpy as np
import torch
import pandas as pd
import torchvision
from torchvision import datasets, models, transforms
import matplotlib.pyplot as plt

%matplotlib inline

### Data loading and visualization

In [42]:
# load training data 
train_df = pd.read_excel("training_data.xlsx")
train_df

,vinegar temperature (T1),vinegar flowrate (F1),baking soda solution temperature (T2),baking soda solution flowrate (F2),reactor outlet temperature (T3),reactor oulet flowrate (F3),pHvalue,reactor level,cooling water temperature (T4),cooling wate flowrate (F4),...,Classification,N,F1,F2,F3,F4,F5,F6,F7,F8
0,37.5,1.83,51.5,1.83,41.5,5.80,4.68,13.20,27,1.69,...,N,1,0,0,0,0,0,0,0,0
1,37.5,1.69,51.5,1.69,41.5,6.21,4.72,13.38,27,1.83,...,N,1,0,0,0,0,0,0,0,0
2,37.5,1.83,51.5,1.83,41.5,6.21,4.71,13.44,27,1.69,...,N,1,0,0,0,0,0,0,0,0
3,37.5,1.69,51.5,1.56,41.5,6.07,4.69,13.08,27,1.83,...,N,1,0,0,0,0,0,0,0,0
4,37.5,1.83,51.5,1.83,41.5,5.94,4.74,13.14,27,1.83,...,N,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2335,37.5,1.69,51.5,1.83,42.5,6.07,4.96,13.44,27,1.69,...,F8,0,0,0,0,0,0,0,0,1
2336,37.5,1.69,51.5,1.69,42.5,6.07,4.98,13.20,27,1.69,...,F8,0,0,0,0,0,0,0,0,1
2337,37.5,1.83,51.5,1.69,42.5,5.94,4.96,13.26,27,1.69,...,F8,0,0,0,0,0,0,0,0,1
2338,37.5,1.83,51.5,1.83,42.5,6.21,4.97,13.08,27,1.69,...,F8,0,0,0,0,0,0,0,0,1
2339,37.5,1.83,51.5,1.69,42.5,5.53,4.99,13.26,27,1.56,...,F8,0,0,0,0,0,0,0,0,1

In [43]:
data_columns = train_df.columns[:12]
data = train_df[data_columns]
data

,vinegar temperature (T1),vinegar flowrate (F1),baking soda solution temperature (T2),baking soda solution flowrate (F2),reactor outlet temperature (T3),reactor oulet flowrate (F3),pHvalue,reactor level,cooling water temperature (T4),cooling wate flowrate (F4),Mixer temperature (T5),Mixer outlet flowrate (F5)
0,37.5,1.83,51.5,1.83,41.5,5.80,4.68,13.20,27,1.69,33.0,4.86
1,37.5,1.69,51.5,1.69,41.5,6.21,4.72,13.38,27,1.83,33.0,4.86
2,37.5,1.83,51.5,1.83,41.5,6.21,4.71,13.44,27,1.69,33.0,4.86
3,37.5,1.69,51.5,1.56,41.5,6.07,4.69,13.08,27,1.83,33.0,4.86
4,37.5,1.83,51.5,1.83,41.5,5.94,4.74,13.14,27,1.83,33.0,4.86
...,...,...,...,...,...,...,...,...,...,...,...,...
2335,37.5,1.69,51.5,1.83,42.5,6.07,4.96,13.44,27,1.69,34.5,0.00
2336,37.5,1.69,51.5,1.69,42.5,6.07,4.98,13.20,27,1.69,34.5,0.00
2337,37.5,1.83,51.5,1.69,42.5,5.94,4.96,13.26,27,1.69,34.5,0.00
2338,37.5,1.83,51.5,1.83,42.5,6.21,4.97,13.08,27,1.69,34.5,0.00
2339,37.5,1.83,51.5,1.69,42.5,5.53,4.99,13.26,27,1.56,34.5,0.00

In [44]:
targets_columns = train_df.columns[13:]
targets = train_df[targets_columns]
targets

      N  F1  F2  F3  F4  F5  F6  F7  F8
0     1   0   0   0   0   0   0   0   0
1     1   0   0   0   0   0   0   0   0
2     1   0   0   0   0   0   0   0   0
3     1   0   0   0   0   0   0   0   0
4     1   0   0   0   0   0   0   0   0
...  ..  ..  ..  ..  ..  ..  ..  ..  ..
2335  0   0   0   0   0   0   0   0   1
2336  0   0   0   0   0   0   0   0   1
2337  0   0   0   0   0   0   0   0   1
2338  0   0   0   0   0   0   0   0   1
2339  0   0   0   0   0   0   0   0   1

[2340 rows x 9 columns]

In [45]:
from sklearn import preprocessing
data.describe()

,vinegar temperature (T1),vinegar flowrate (F1),baking soda solution temperature (T2),baking soda solution flowrate (F2),reactor outlet temperature (T3),reactor oulet flowrate (F3),pHvalue,reactor level,cooling water temperature (T4),cooling wate flowrate (F4),Mixer temperature (T5),Mixer outlet flowrate (F5)
count,2340.000000,2340.000000,2340.000000,2340.000000,2340.000000,2340.000000,2340.000000,2340.0000,2340.0,2340.000000,2340.000000,2340.000000
mean,36.444231,1.450504,48.722222,1.616415,40.398504,4.952235,5.185009,13.4125,27.0,1.477115,33.555342,4.212256
std,2.986142,0.542205,7.858421,0.224898,4.060685,1.622343,1.012208,1.4193,0.0,0.531907,2.337089,1.533118
min,28.000000,0.000000,26.500000,1.020000,29.500000,1.220000,2.990000,9.6300,27.0,0.000000,28.000000,0.000000
25%,37.500000,1.420000,51.500000,1.560000,39.500000,3.780000,4.820000,13.0800,27.0,1.560000,32.000000,4.320000
50%,37.500000,1.690000,51.500000,1.690000,42.000000,5.940000,4.930000,13.2600,27.0,1.690000,34.000000,4.730000
75%,37.500000,1.690000,51.500000,1.690000,42.500000,6.210000,5.120000,13.5500,27.0,1.690000,35.000000,5.130000
max,37.500000,2.370000,51.500000,2.640000,46.000000,6.750000,8.330000,18.2800,27.0,1.960000,37.500000,5.530000

In [46]:
x = data.values #returns a numpy array
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
data_scaled = pd.DataFrame(x_scaled)
data_scaled.columns = data.columns
data_scaled

,vinegar temperature (T1),vinegar flowrate (F1),baking soda solution temperature (T2),baking soda solution flowrate (F2),reactor outlet temperature (T3),reactor oulet flowrate (F3),pHvalue,reactor level,cooling water temperature (T4),cooling wate flowrate (F4),Mixer temperature (T5),Mixer outlet flowrate (F5)
0,1.0,0.772152,1.0,0.500000,0.727273,0.828210,0.316479,0.412717,0.0,0.862245,0.526316,0.878843
1,1.0,0.713080,1.0,0.413580,0.727273,0.902351,0.323970,0.433526,0.0,0.933673,0.526316,0.878843
2,1.0,0.772152,1.0,0.500000,0.727273,0.902351,0.322097,0.440462,0.0,0.862245,0.526316,0.878843
3,1.0,0.713080,1.0,0.333333,0.727273,0.877034,0.318352,0.398844,0.0,0.933673,0.526316,0.878843
4,1.0,0.772152,1.0,0.500000,0.727273,0.853526,0.327715,0.405780,0.0,0.933673,0.526316,0.878843
...,...,...,...,...,...,...,...,...,...,...,...,...
2335,1.0,0.713080,1.0,0.500000,0.787879,0.877034,0.368914,0.440462,0.0,0.862245,0.684211,0.000000
2336,1.0,0.713080,1.0,0.413580,0.787879,0.877034,0.372659,0.412717,0.0,0.862245,0.684211,0.000000
2337,1.0,0.772152,1.0,0.413580,0.787879,0.853526,0.368914,0.419653,0.0,0.862245,0.684211,0.000000
2338,1.0,0.772152,1.0,0.500000,0.787879,0.902351,0.370787,0.398844,0.0,0.862245,0.684211,0.000000
2339,1.0,0.772152,1.0,0.413580,0.787879,0.779385,0.374532,0.419653,0.0,0.795918,0.684211,0.000000

In [47]:
data_scaled = train_df
data_scaled.describe()

,vinegar temperature (T1),vinegar flowrate (F1),baking soda solution temperature (T2),baking soda solution flowrate (F2),reactor outlet temperature (T3),reactor oulet flowrate (F3),pHvalue,reactor level,cooling water temperature (T4),cooling wate flowrate (F4),...,Mixer outlet flowrate (F5),N,F1,F2,F3,F4,F5,F6,F7,F8
count,2340.000000,2340.000000,2340.000000,2340.000000,2340.000000,2340.000000,2340.000000,2340.0000,2340.0,2340.000000,...,2340.000000,2340.000000,2340.000000,2340.000000,2340.000000,2340.000000,2340.000000,2340.000000,2340.000000,2340.000000
mean,36.444231,1.450504,48.722222,1.616415,40.398504,4.952235,5.185009,13.4125,27.0,1.477115,...,4.212256,0.111111,0.111111,0.111111,0.111111,0.111111,0.111111,0.111111,0.111111,0.111111
std,2.986142,0.542205,7.858421,0.224898,4.060685,1.622343,1.012208,1.4193,0.0,0.531907,...,1.533118,0.314337,0.314337,0.314337,0.314337,0.314337,0.314337,0.314337,0.314337,0.314337
min,28.000000,0.000000,26.500000,1.020000,29.500000,1.220000,2.990000,9.6300,27.0,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,37.500000,1.420000,51.500000,1.560000,39.500000,3.780000,4.820000,13.0800,27.0,1.560000,...,4.320000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,37.500000,1.690000,51.500000,1.690000,42.000000,5.940000,4.930000,13.2600,27.0,1.690000,...,4.730000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,37.500000,1.690000,51.500000,1.690000,42.500000,6.210000,5.120000,13.5500,27.0,1.690000,...,5.130000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,37.500000,2.370000,51.500000,2.640000,46.000000,6.750000,8.330000,18.2800,27.0,1.960000,...,5.530000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

### load and divide the data

In [48]:
all_data = train_df

In [49]:
all_data

,vinegar temperature (T1),vinegar flowrate (F1),baking soda solution temperature (T2),baking soda solution flowrate (F2),reactor outlet temperature (T3),reactor oulet flowrate (F3),pHvalue,reactor level,cooling water temperature (T4),cooling wate flowrate (F4),...,Classification,N,F1,F2,F3,F4,F5,F6,F7,F8
0,37.5,1.83,51.5,1.83,41.5,5.80,4.68,13.20,27,1.69,...,N,1,0,0,0,0,0,0,0,0
1,37.5,1.69,51.5,1.69,41.5,6.21,4.72,13.38,27,1.83,...,N,1,0,0,0,0,0,0,0,0
2,37.5,1.83,51.5,1.83,41.5,6.21,4.71,13.44,27,1.69,...,N,1,0,0,0,0,0,0,0,0
3,37.5,1.69,51.5,1.56,41.5,6.07,4.69,13.08,27,1.83,...,N,1,0,0,0,0,0,0,0,0
4,37.5,1.83,51.5,1.83,41.5,5.94,4.74,13.14,27,1.83,...,N,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2335,37.5,1.69,51.5,1.83,42.5,6.07,4.96,13.44,27,1.69,...,F8,0,0,0,0,0,0,0,0,1
2336,37.5,1.69,51.5,1.69,42.5,6.07,4.98,13.20,27,1.69,...,F8,0,0,0,0,0,0,0,0,1
2337,37.5,1.83,51.5,1.69,42.5,5.94,4.96,13.26,27,1.69,...,F8,0,0,0,0,0,0,0,0,1
2338,37.5,1.83,51.5,1.83,42.5,6.21,4.97,13.08,27,1.69,...,F8,0,0,0,0,0,0,0,0,1
2339,37.5,1.83,51.5,1.69,42.5,5.53,4.99,13.26,27,1.56,...,F8,0,0,0,0,0,0,0,0,1

In [50]:
class_column = []
for index, row in all_data.iterrows():
    index = 0
    
    for i in row[13:]:
        if i == 1.0:
            class_column.append(index)
            break
        index += 1
           
print(class_column)
all_data["target"] = class_column
all_data

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8]

,vinegar temperature (T1),vinegar flowrate (F1),baking soda solution temperature (T2),baking soda solution flowrate (F2),reactor outlet temperature (T3),reactor oulet flowrate (F3),pHvalue,reactor level,cooling water temperature (T4),cooling wate flowrate (F4),...,N,F1,F2,F3,F4,F5,F6,F7,F8,target
0,37.5,1.83,51.5,1.83,41.5,5.80,4.68,13.20,27,1.69,...,1,0,0,0,0,0,0,0,0,0
1,37.5,1.69,51.5,1.69,41.5,6.21,4.72,13.38,27,1.83,...,1,0,0,0,0,0,0,0,0,0
2,37.5,1.83,51.5,1.83,41.5,6.21,4.71,13.44,27,1.69,...,1,0,0,0,0,0,0,0,0,0
3,37.5,1.69,51.5,1.56,41.5,6.07,4.69,13.08,27,1.83,...,1,0,0,0,0,0,0,0,0,0
4,37.5,1.83,51.5,1.83,41.5,5.94,4.74,13.14,27,1.83,...,1,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2335,37.5,1.69,51.5,1.83,42.5,6.07,4.96,13.44,27,1.69,...,0,0,0,0,0,0,0,0,1,8
2336,37.5,1.69,51.5,1.69,42.5,6.07,4.98,13.20,27,1.69,...,0,0,0,0,0,0,0,0,1,8
2337,37.5,1.83,51.5,1.69,42.5,5.94,4.96,13.26,27,1.69,...,0,0,0,0,0,0,0,0,1,8
2338,37.5,1.83,51.5,1.83,42.5,6.21,4.97,13.08,27,1.69,...,0,0,0,0,0,0,0,0,1,8
2339,37.5,1.83,51.5,1.69,42.5,5.53,4.99,13.26,27,1.56,...,0,0,0,0,0,0,0,0,1,8

In [51]:
all_data_shuffled = all_data.sample(frac=1)
all_data_shuffled

,vinegar temperature (T1),vinegar flowrate (F1),baking soda solution temperature (T2),baking soda solution flowrate (F2),reactor outlet temperature (T3),reactor oulet flowrate (F3),pHvalue,reactor level,cooling water temperature (T4),cooling wate flowrate (F4),...,N,F1,F2,F3,F4,F5,F6,F7,F8,target
1531,37.5,1.56,51.5,1.56,42.5,3.65,4.96,16.43,27,1.69,...,0,0,0,0,0,1,0,0,0,5
1495,37.5,1.69,51.5,1.69,42.0,3.92,4.91,16.38,27,1.56,...,0,0,0,0,0,1,0,0,0,5
2227,37.5,1.83,51.5,1.69,42.0,6.21,4.97,13.84,27,1.69,...,0,0,0,0,0,0,0,0,1,8
294,37.5,0.00,51.5,1.69,43.5,1.49,6.68,11.91,27,1.56,...,0,1,0,0,0,0,0,0,0,1
2250,37.5,1.69,51.5,1.69,42.5,6.07,4.98,13.20,27,1.56,...,0,0,0,0,0,0,0,0,1,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1523,37.5,1.69,51.5,1.69,42.0,3.92,4.94,16.67,27,1.69,...,0,0,0,0,0,1,0,0,0,5
53,37.5,1.69,51.5,1.69,41.5,4.19,4.87,13.20,27,1.69,...,1,0,0,0,0,0,0,0,0,0
965,37.5,1.56,51.5,1.02,39.5,4.46,4.15,12.54,27,1.56,...,0,0,0,1,0,0,0,0,0,3
1289,37.5,1.83,26.5,1.69,31.0,6.07,5.02,13.44,27,1.56,...,0,0,0,0,1,0,0,0,0,4
2177,37.5,1.42,51.5,1.69,42.0,6.21,4.94,13.20,27,1.69,...,0,0,0,0,0,0,0,0,1,8

In [52]:
data_columns, targets_columns = all_data_shuffled.columns[:11], all_data_shuffled.columns[11:-2]
all_data_shuffled = all_data_shuffled.drop(targets_columns, axis=1)
all_data_shuffled

,vinegar temperature (T1),vinegar flowrate (F1),baking soda solution temperature (T2),baking soda solution flowrate (F2),reactor outlet temperature (T3),reactor oulet flowrate (F3),pHvalue,reactor level,cooling water temperature (T4),cooling wate flowrate (F4),Mixer temperature (T5),F8,target
1531,37.5,1.56,51.5,1.56,42.5,3.65,4.96,16.43,27,1.69,33.0,0,5
1495,37.5,1.69,51.5,1.69,42.0,3.92,4.91,16.38,27,1.56,33.0,0,5
2227,37.5,1.83,51.5,1.69,42.0,6.21,4.97,13.84,27,1.69,34.0,1,8
294,37.5,0.00,51.5,1.69,43.5,1.49,6.68,11.91,27,1.56,35.5,0,1
2250,37.5,1.69,51.5,1.69,42.5,6.07,4.98,13.20,27,1.56,34.5,1,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1523,37.5,1.69,51.5,1.69,42.0,3.92,4.94,16.67,27,1.69,33.0,0,5
53,37.5,1.69,51.5,1.69,41.5,4.19,4.87,13.20,27,1.69,34.0,0,0
965,37.5,1.56,51.5,1.02,39.5,4.46,4.15,12.54,27,1.56,32.0,0,3
1289,37.5,1.83,26.5,1.69,31.0,6.07,5.02,13.44,27,1.56,29.0,0,4
2177,37.5,1.42,51.5,1.69,42.0,6.21,4.94,13.20,27,1.69,34.0,1,8

In [31]:
targets_columns = all_data_shuffled.columns[-1]
targets_columns

'target'

In [32]:
#Convert targets to float 
all_data_shuffled[targets_columns] = all_data_shuffled[targets_columns].astype(float)
all_data_shuffled[data_columns].info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2340 entries, 1249 to 1729
Data columns (total 11 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   vinegar temperature (T1)               2340 non-null   float64
 1   vinegar flowrate (F1)                  2340 non-null   float64
 2   baking soda solution temperature (T2)  2340 non-null   float64
 3   baking soda solution flowrate (F2)     2340 non-null   float64
 4   reactor outlet temperature (T3)        2340 non-null   float64
 5   reactor oulet flowrate (F3)            2340 non-null   float64
 6   pHvalue                                2340 non-null   float64
 7   reactor level                          2340 non-null   float64
 8   cooling water temperature (T4)         2340 non-null   int64
 9   cooling wate flowrate (F4)             2340 non-null   float64
 10  Mixer temperature (T5)                 2340 non-null   float64
dtypes: float64(10), int64(1)
memory usage: 219.4 KB

In [33]:
import torch.utils.data as data_utils
data_range = range(0,11)
target_range = [-1]
b_size = 1
#train
training_data = torch.utils.data.DataLoader(torch.tensor(all_data_shuffled.iloc[:1638, data_range].values), batch_size=b_size, num_workers=0)
training_target = torch.utils.data.DataLoader(torch.tensor(all_data_shuffled.iloc[:1638, target_range].values, dtype=torch.long), batch_size=b_size, num_workers=0)


# valid
validation_data = torch.utils.data.DataLoader(torch.tensor(all_data_shuffled.iloc[1638:2106, data_range].values), batch_size=b_size, num_workers=0)
validation_target = torch.utils.data.DataLoader(torch.tensor(all_data_shuffled.iloc[1638:2106, target_range].values, dtype=torch.long), batch_size=b_size, num_workers=0)


# test
testing_data = torch.utils.data.DataLoader(torch.tensor(all_data_shuffled.iloc[2106:, data_range].values), batch_size=b_size, num_workers=0)
testing_target = torch.utils.data.DataLoader(torch.tensor(all_data_shuffled.iloc[2106:, target_range].values, dtype=torch.long), batch_size=b_size, num_workers=0)

In [34]:
for data, target in zip(training_data, training_target):
    print(data)
    print(target.resize_(1))
    break

tensor([[37.5000,  1.6900, 26.5000,  1.6900, 30.5000,  6.2100,  4.9800, 13.9000,
         27.0000,  1.8300, 29.0000]], dtype=torch.float64)
tensor([4])

### Develop the model

In [35]:
import torch.nn as nn
import torch.nn.functional as F

# define the CNN architecture
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        # linear layer (64 * 4 * 4 -> 500)
        self.fc1 = nn.Linear(11, 11)
        # linear layer (500 -> 10)
        self.fc2 = nn.Linear(11, 9)
        
        # dropout layer (p=0.25)
        self.dropout = nn.Dropout(0.2)

    def forward(self, x):
        x = F.relu(self.fc1(x))
        # add dropout layer
        x = self.dropout(x)
        # add 1st hidden layer, with relu activation function
        x = self.fc2(x)
        # add dropout layer
      
        return x

# create a complete CNN
model = Net()
print(model)

Net(
  (fc1): Linear(in_features=11, out_features=11, bias=True)
  (fc2): Linear(in_features=11, out_features=9, bias=True)
  (dropout): Dropout(p=0.2, inplace=False)
)

In [36]:
import torch.optim as optim

# specify loss function (categorical cross-entropy)
criterion = nn.CrossEntropyLoss()

# specify optimizer
optimizer = optim.SGD(model.parameters(), lr=0.0009)

In [38]:
# number of epochs to train the model
n_epochs = 1000

valid_loss_min = np.Inf # track change in validation loss

for epoch in range(1, n_epochs+1):

    # keep track of training and validation loss
    train_loss = 0.0
    valid_loss = 0.0
    index = 0
    ###################
    # train the model #
    ###################
    model.train()
    for data, target in zip(training_data, training_target):
        # clear the gradients of all optimized variables
        optimizer.zero_grad()
        # forward pass: compute predicted outputs by passing inputs to the model
        output = model(data.float())
        # calculate the batch loss
        loss = criterion(output, target.resize_(1))
        # backward pass: compute gradient of the loss with respect to model parameters
        loss.backward()
        # perform a single optimization step (parameter update)
        optimizer.step()
        # update training loss
        train_loss += loss.item()*data.size(0)
    ######################    
    # validate the model #
    ######################
    model.eval()
    for data, target in zip(validation_data, validation_target):
        # forward pass: compute predicted outputs by passing inputs to the model
        output = model(data.float())
        # calculate the batch loss
        loss = criterion(output, target.resize_(1))
        # update average validation loss 
        valid_loss += loss.item()*data.size(0)
    
    # calculate average losses
    train_loss = train_loss/len(training_data)
    valid_loss = valid_loss/len(validation_data)
        
    # print training/validation statistics 
    print('Epoch: {} \tTraining Loss: {:.6f} \tValidation Loss: {:.6f}'.format(
        epoch, train_loss, valid_loss))
    
    # save model if validation loss has decreased
    if valid_loss <= valid_loss_min:
        print('Validation loss decreased ({:.6f} --> {:.6f}).  Saving model ...'.format(
        valid_loss_min,
        valid_loss))
        torch.save(model.state_dict(), 'model_cifar.pt')
        valid_loss_min = valid_loss

Epoch: 1 	Training Loss: 1.832343 	Validation Loss: 1.720715
Validation loss decreased (inf --> 1.720715).  Saving model ...
Epoch: 2 	Training Loss: 1.827285 	Validation Loss: 1.699166
Validation loss decreased (1.720715 --> 1.699166).  Saving model ...
Epoch: 3 	Training Loss: 1.809718 	Validation Loss: 1.684302
Validation loss decreased (1.699166 --> 1.684302).  Saving model ...
Epoch: 4 	Training Loss: 1.806663 	Validation Loss: 1.693561
Epoch: 5 	Training Loss: 1.773202 	Validation Loss: 1.644610
Validation loss decreased (1.684302 --> 1.644610).  Saving model ...
Epoch: 6 	Training Loss: 1.794379 	Validation Loss: 1.638922
Validation loss decreased (1.644610 --> 1.638922).  Saving model ...
Epoch: 7 	Training Loss: 1.768546 	Validation Loss: 1.633607
Validation loss decreased (1.638922 --> 1.633607).  Saving model ...
Epoch: 8 	Training Loss: 1.751072 	Validation Loss: 1.639458
Epoch: 9 	Training Loss: 1.762935 	Validation Loss: 1.585467
Validation loss decreased (1.633607 --> 1.585467).  Saving model ...
Epoch: 10 	Training Loss: 1.776902 	Validation Loss: 1.578936
Validation loss decreased (1.585467 --> 1.578936).  Saving model ...
Epoch: 11 	Training Loss: 1.722822 	Validation Loss: 1.571665
Validation loss decreased (1.578936 --> 1.571665).  Saving model ...
Epoch: 12 	Training Loss: 1.769517 	Validation Loss: 1.578699
Epoch: 13 	Training Loss: 1.731101 	Validation Loss: 1.555492
Validation loss decreased (1.571665 --> 1.555492).  Saving model ...
Epoch: 14 	Training Loss: 1.722119 	Validation Loss: 1.554432
Validation loss decreased (1.555492 --> 1.554432).  Saving model ...
Epoch: 15 	Training Loss: 1.728881 	Validation Loss: 1.566544
Epoch: 16 	Training Loss: 1.707732 	Validation Loss: 1.678362
Epoch: 17 	Training Loss: 1.719275 	Validation Loss: 1.523538
Validation loss decreased (1.554432 --> 1.523538).  Saving model ...
Epoch: 18 	Training Loss: 1.726166 	Validation Loss: 1.519284
Validation loss decreased (1.523538 --> 1.519284).  Saving model ...
Epoch: 19 	Training Loss: 1.691323 	Validation Loss: 1.500741
Validation loss decreased (1.519284 --> 1.500741).  Saving model ...
Epoch: 20 	Training Loss: 1.698536 	Validation Loss: 1.541621
Epoch: 21 	Training Loss: 1.707075 	Validation Loss: 1.492046
Validation loss decreased (1.500741 --> 1.492046).  Saving model ...
Epoch: 22 	Training Loss: 1.672517 	Validation Loss: 1.513470
Epoch: 23 	Training Loss: 1.711430 	Validation Loss: 1.490864
Validation loss decreased (1.492046 --> 1.490864).  Saving model ...
Epoch: 24 	Training Loss: 1.676453 	Validation Loss: 1.491457
Epoch: 25 	Training Loss: 1.715586 	Validation Loss: 1.509064
Epoch: 26 	Training Loss: 1.684537 	Validation Loss: 1.468576
Validation loss decreased (1.490864 --> 1.468576).  Saving model ...
Epoch: 27 	Training Loss: 1.687531 	Validation Loss: 1.454834
Validation loss decreased (1.468576 --> 1.454834).  Saving model ...
Epoch: 28 	Training Loss: 1.671375 	Validation Loss: 1.695397
Epoch: 29 	Training Loss: 1.663888 	Validation Loss: 1.441525
Validation loss decreased (1.454834 --> 1.441525).  Saving model ...
Epoch: 30 	Training Loss: 1.674040 	Validation Loss: 1.459720
Epoch: 31 	Training Loss: 1.663531 	Validation Loss: 1.490509
Epoch: 32 	Training Loss: 1.702645 	Validation Loss: 1.570064
Epoch: 33 	Training Loss: 1.649053 	Validation Loss: 1.436439
Validation loss decreased (1.441525 --> 1.436439).  Saving model ...
Epoch: 34 	Training Loss: 1.705351 	Validation Loss: 1.437651
Epoch: 35 	Training Loss: 1.679983 	Validation Loss: 1.577618
Epoch: 36 	Training Loss: 1.667076 	Validation Loss: 1.452103
Epoch: 37 	Training Loss: 1.691824 	Validation Loss: 1.447870
Epoch: 38 	Training Loss: 1.659579 	Validation Loss: 1.426630
Validation loss decreased (1.436439 --> 1.426630).  Saving model ...
Epoch: 39 	Training Loss: 1.647917 	Validation Loss: 1.457949
Epoch: 40 	Training Loss: 1.646570 	Validation Loss: 1.431504
Epoch: 41 	Training Loss: 1.629796 	Validation Loss: 1.546444
Epoch: 42 	Training Loss: 1.661715 	Validation Loss: 1.424869
Validation loss decreased (1.426630 --> 1.424869).  Saving model ...
Epoch: 43 	Training Loss: 1.647616 	Validation Loss: 1.389697
Validation loss decreased (1.424869 --> 1.389697).  Saving model ...
Epoch: 44 	Training Loss: 1.671744 	Validation Loss: 1.430630
Epoch: 45 	Training Loss: 1.693949 	Validation Loss: 1.405423
Epoch: 46 	Training Loss: 1.653900 	Validation Loss: 1.423200
Epoch: 47 	Training Loss: 1.645323 	Validation Loss: 1.412677
Epoch: 48 	Training Loss: 1.677089 	Validation Loss: 1.418700
Epoch: 49 	Training Loss: 1.669106 	Validation Loss: 1.388738
Validation loss decreased (1.389697 --> 1.388738).  Saving model ...
Epoch: 50 	Training Loss: 1.643939 	Validation Loss: 1.383201
Validation loss decreased (1.388738 --> 1.383201).  Saving model ...
Epoch: 51 	Training Loss: 1.604405 	Validation Loss: 1.376104
Validation loss decreased (1.383201 --> 1.376104).  Saving model ...
Epoch: 52 	Training Loss: 1.626501 	Validation Loss: 1.406146
Epoch: 53 	Training Loss: 1.679793 	Validation Loss: 1.633787
Epoch: 54 	Training Loss: 1.649966 	Validation Loss: 1.403030
Epoch: 55 	Training Loss: 1.636595 	Validation Loss: 1.410491
Epoch: 56 	Training Loss: 1.652392 	Validation Loss: 1.391026
Epoch: 57 	Training Loss: 1.644540 	Validation Loss: 1.365152
Validation loss decreased (1.376104 --> 1.365152).  Saving model ...
Epoch: 58 	Training Loss: 1.649145 	Validation Loss: 1.411672
Epoch: 59 	Training Loss: 1.638458 	Validation Loss: 1.379918
Epoch: 60 	Training Loss: 1.665266 	Validation Loss: 1.392189
Epoch: 61 	Training Loss: 1.632421 	Validation Loss: 1.370380

KeyboardInterrupt:

In [39]:
model.load_state_dict(torch.load('model_cifar.pt'))

In [40]:
dataaaa = torch.tensor([])
targetttt = []
prediction_list = []
summ = 0
for data, target in zip(testing_data, testing_target):    
    model.eval()
    output = model(data.float())
    loss = nn.Softmax()
    print(f"correct is {target}")
    pred = torch.max(loss(output))
    prediction_list.append(pred.item() * 100)
    print(f"pred is {prediction_list[-1]}")
    summ += 1
print(sum(prediction_list)/summ)

correct is tensor([[5]])
pred is 34.2331200838089
correct is tensor([[3]])
pred is 30.29290735721588
correct is tensor([[2]])
pred is 22.363945841789246
correct is tensor([[7]])
pred is 72.40289449691772
correct is tensor([[3]])
pred is 30.141732096672058
correct is tensor([[1]])
pred is 20.307601988315582
correct is tensor([[0]])
pred is 24.71678853034973
correct is tensor([[1]])
pred is 20.307601988315582
correct is tensor([[1]])
pred is 20.307601988315582
correct is tensor([[6]])
pred is 20.307601988315582
correct is tensor([[3]])
pred is 28.02545726299286
correct is tensor([[0]])
pred is 24.709388613700867
correct is tensor([[2]])
pred is 22.088436782360077
correct is tensor([[4]])
pred is 20.307601988315582
correct is tensor([[7]])
pred is 73.27935099601746
correct is tensor([[6]])
pred is 20.307601988315582
correct is tensor([[4]])
pred is 20.307601988315582
correct is tensor([[2]])
pred is 20.307601988315582
correct is tensor([[8]])
pred is 24.37533289194107
correct is tensor([[0]])
pred is 24.70361888408661
correct is tensor([[7]])
pred is 79.03770208358765
correct is tensor([[6]])
pred is 20.307601988315582
correct is tensor([[7]])
pred is 72.40289449691772
correct is tensor([[2]])
pred is 22.415712475776672
correct is tensor([[5]])
pred is 33.62603187561035
correct is tensor([[8]])
pred is 24.605317413806915
correct is tensor([[2]])
pred is 22.03231006860733
correct is tensor([[3]])
pred is 29.97579574584961
correct is tensor([[3]])
pred is 25.37013590335846
correct is tensor([[0]])
pred is 24.705035984516144
correct is tensor([[8]])
pred is 23.890262842178345
correct is tensor([[8]])
pred is 24.800898134708405
correct is tensor([[4]])
pred is 20.307601988315582
correct is tensor([[3]])
pred is 23.301763832569122
correct is tensor([[1]])
pred is 20.307601988315582
correct is tensor([[2]])
pred is 20.307601988315582
correct is tensor([[7]])
pred is 73.94253611564636
correct is tensor([[5]])
pred is 34.13169085979462
correct is tensor([[7]])
pred is 74.28662180900574
correct is tensor([[4]])
pred is 20.307601988315582
correct is tensor([[8]])
pred is 24.79182928800583
correct is tensor([[1]])
pred is 20.307601988315582
correct is tensor([[4]])
pred is 20.307601988315582
correct is tensor([[6]])
pred is 20.307601988315582
correct is tensor([[0]])
pred is 24.229784309864044
correct is tensor([[1]])
pred is 20.307601988315582
correct is tensor([[3]])
pred is 29.418981075286865
correct is tensor([[5]])
pred is 33.71311128139496
correct is tensor([[7]])
pred is 78.28798294067383
correct is tensor([[0]])
pred is 24.21838492155075
correct is tensor([[2]])
pred is 22.402091324329376
correct is tensor([[2]])
pred is 22.23234921693802
correct is tensor([[3]])
pred is 30.165928602218628
correct is tensor([[8]])
pred is 24.041326344013214
correct is tensor([[5]])
pred is 34.28776264190674
correct is tensor([[4]])
pred is 20.307601988315582
correct is tensor([[8]])
pred is 23.342572152614594
correct is tensor([[8]])
pred is 24.371318519115448
correct is tensor([[4]])
pred is 20.307601988315582
correct is tensor([[4]])
pred is 20.307601988315582
correct is tensor([[6]])
pred is 20.307601988315582
correct is tensor([[1]])
pred is 20.307601988315582
correct is tensor([[4]])
pred is 20.307601988315582
correct is tensor([[8]])
pred is 24.430158734321594
correct is tensor([[3]])
pred is 25.46173632144928
correct is tensor([[2]])
pred is 22.05389440059662
correct is tensor([[8]])
pred is 24.52404648065567
correct is tensor([[0]])
pred is 24.55492913722992
correct is tensor([[5]])
pred is 33.65837633609772
correct is tensor([[5]])
pred is 33.402061462402344
correct is tensor([[1]])
pred is 20.307601988315582
correct is tensor([[5]])
pred is 34.373122453689575
correct is tensor([[6]])
pred is 20.307601988315582
correct is tensor([[0]])
pred is 24.681778252124786
correct is tensor([[7]])
pred is 74.70158338546753
correct is tensor([[8]])
pred is 24.5813250541687
correct is tensor([[1]])
pred is 20.307601988315582
correct is tensor([[7]])
pred is 73.94253611564636
correct is tensor([[1]])
pred is 20.307601988315582
correct is tensor([[4]])
pred is 20.307601988315582
correct is tensor([[7]])
pred is 78.15074324607849
correct is tensor([[4]])
pred is 20.307601988315582
correct is tensor([[0]])
pred is 24.5185524225235
correct is tensor([[4]])
pred is 20.307601988315582
correct is tensor([[0]])
pred is 24.48352724313736
correct is tensor([[1]])
pred is 20.307601988315582
correct is tensor([[4]])
pred is 20.307601988315582
correct is tensor([[0]])
pred is 24.378114938735962
correct is tensor([[0]])
pred is 23.811273276805878
correct is tensor([[3]])
pred is 30.051836371421814
correct is tensor([[3]])
pred is 29.18892204761505
correct is tensor([[8]])
pred is 24.54293668270111
correct is tensor([[0]])
pred is 24.723942577838898
correct is tensor([[6]])
pred is 20.307601988315582
correct is tensor([[8]])
pred is 25.12480318546295
correct is tensor([[7]])
pred is 75.12447834014893
correct is tensor([[5]])
pred is 33.84409248828888
correct is tensor([[5]])
pred is 33.65837633609772
correct is tensor([[4]])
pred is 20.307601988315582
correct is tensor([[1]])
pred is 20.307601988315582
correct is tensor([[5]])
pred is 33.20881724357605
correct is tensor([[3]])
pred is 28.81026566028595
correct is tensor([[4]])
pred is 20.307601988315582
correct is tensor([[7]])
pred is 74.70158338546753
correct is tensor([[0]])
pred is 23.342572152614594
correct is tensor([[0]])
pred is 24.009796977043152
correct is tensor([[7]])
pred is 75.12447834014893
correct is tensor([[7]])
pred is 72.82915711402893
correct is tensor([[6]])
pred is 20.307601988315582
correct is tensor([[5]])
pred is 34.459492564201355
correct is tensor([[6]])
pred is 20.307601988315582
correct is tensor([[2]])
pred is 21.89392000436783
correct is tensor([[8]])
pred is 24.80643391609192
correct is tensor([[8]])
pred is 24.297739565372467
correct is tensor([[3]])
pred is 29.621371626853943
correct is tensor([[4]])
pred is 20.307601988315582
correct is tensor([[6]])
pred is 20.307601988315582
correct is tensor([[1]])
pred is 20.307601988315582
correct is tensor([[7]])
pred is 73.27935099601746
correct is tensor([[6]])
pred is 20.307601988315582
correct is tensor([[8]])
pred is 24.592462182044983
correct is tensor([[1]])
pred is 20.307601988315582

<ipython-input-40-f197845c21e8>:10: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  pred = torch.max(loss(output))

correct is tensor([[1]])
pred is 20.307601988315582
correct is tensor([[2]])
pred is 23.593923449516296
correct is tensor([[8]])
pred is 24.64713156223297
correct is tensor([[7]])
pred is 74.28378462791443
correct is tensor([[6]])
pred is 20.307601988315582
correct is tensor([[2]])
pred is 22.41557389497757
correct is tensor([[4]])
pred is 20.307601988315582
correct is tensor([[0]])
pred is 24.797430634498596
correct is tensor([[6]])
pred is 20.307601988315582
correct is tensor([[8]])
pred is 24.63163584470749
correct is tensor([[6]])
pred is 20.307601988315582
correct is tensor([[6]])
pred is 20.307601988315582
correct is tensor([[4]])
pred is 20.307601988315582
correct is tensor([[0]])
pred is 24.677494168281555
correct is tensor([[0]])
pred is 24.781139194965363
correct is tensor([[4]])
pred is 20.307601988315582
correct is tensor([[4]])
pred is 20.307601988315582
correct is tensor([[2]])
pred is 20.830529928207397
correct is tensor([[1]])
pred is 20.307601988315582
correct is tensor([[8]])
pred is 24.683713912963867
correct is tensor([[2]])
pred is 22.133511304855347
correct is tensor([[0]])
pred is 24.775463342666626
correct is tensor([[3]])
pred is 30.918729305267334
correct is tensor([[4]])
pred is 20.307601988315582
correct is tensor([[5]])
pred is 34.27997827529907
correct is tensor([[3]])
pred is 25.129422545433044
correct is tensor([[6]])
pred is 20.307601988315582
correct is tensor([[6]])
pred is 20.307601988315582
correct is tensor([[4]])
pred is 20.307601988315582
correct is tensor([[0]])
pred is 23.924128711223602
correct is tensor([[5]])
pred is 34.261736273765564
correct is tensor([[0]])
pred is 23.266053199768066
correct is tensor([[0]])
pred is 24.330545961856842
correct is tensor([[3]])
pred is 29.537639021873474
correct is tensor([[3]])
pred is 26.43912136554718
correct is tensor([[4]])
pred is 20.307601988315582
correct is tensor([[8]])
pred is 24.25578236579895
correct is tensor([[5]])
pred is 33.04052948951721
correct is tensor([[8]])
pred is 24.24425482749939
correct is tensor([[6]])
pred is 20.307601988315582
correct is tensor([[1]])
pred is 20.307601988315582
correct is tensor([[4]])
pred is 20.307601988315582
correct is tensor([[6]])
pred is 20.307601988315582
correct is tensor([[6]])
pred is 20.307601988315582
correct is tensor([[1]])
pred is 20.307601988315582
correct is tensor([[7]])
pred is 72.06901907920837
correct is tensor([[4]])
pred is 20.307601988315582
correct is tensor([[7]])
pred is 74.71624612808228
correct is tensor([[4]])
pred is 20.307601988315582
correct is tensor([[1]])
pred is 20.307601988315582
correct is tensor([[0]])
pred is 23.30455482006073
correct is tensor([[1]])
pred is 20.307601988315582
correct is tensor([[4]])
pred is 20.307601988315582
correct is tensor([[8]])
pred is 24.650631844997406
correct is tensor([[6]])
pred is 20.307601988315582
correct is tensor([[7]])
pred is 73.94253611564636
correct is tensor([[2]])
pred is 19.979380071163177
correct is tensor([[0]])
pred is 24.247688055038452
correct is tensor([[5]])
pred is 33.761438727378845
correct is tensor([[2]])
pred is 22.611844539642334
correct is tensor([[7]])
pred is 77.49736905097961
correct is tensor([[3]])
pred is 30.774661898612976
correct is tensor([[3]])
pred is 25.46173632144928
correct is tensor([[6]])
pred is 20.307601988315582
correct is tensor([[0]])
pred is 24.42980855703354
correct is tensor([[2]])
pred is 22.226732969284058
correct is tensor([[3]])
pred is 25.648599863052368
correct is tensor([[6]])
pred is 20.307601988315582
correct is tensor([[1]])
pred is 20.307601988315582
correct is tensor([[0]])
pred is 24.087300896644592
correct is tensor([[6]])
pred is 20.307601988315582
correct is tensor([[8]])
pred is 24.500492215156555
correct is tensor([[6]])
pred is 20.307601988315582
correct is tensor([[7]])
pred is 75.66706538200378
correct is tensor([[1]])
pred is 20.307601988315582
correct is tensor([[7]])
pred is 74.22775626182556
correct is tensor([[8]])
pred is 24.52404648065567
correct is tensor([[6]])
pred is 20.307601988315582
correct is tensor([[8]])
pred is 24.716129899024963
correct is tensor([[0]])
pred is 24.544206261634827
correct is tensor([[8]])
pred is 24.430158734321594
correct is tensor([[5]])
pred is 33.58150124549866
correct is tensor([[0]])
pred is 24.29642528295517
correct is tensor([[2]])
pred is 22.102314233779907
correct is tensor([[3]])
pred is 29.746714234352112
correct is tensor([[6]])
pred is 20.307601988315582
correct is tensor([[8]])
pred is 23.44861477613449
correct is tensor([[0]])
pred is 24.183332920074463
correct is tensor([[0]])
pred is 24.79214072227478
correct is tensor([[6]])
pred is 20.307601988315582
correct is tensor([[8]])
pred is 24.591028690338135
correct is tensor([[1]])
pred is 20.307601988315582
correct is tensor([[0]])
pred is 24.271954596042633
correct is tensor([[4]])
pred is 20.307601988315582
correct is tensor([[0]])
pred is 24.762775003910065
correct is tensor([[8]])
pred is 24.01956468820572
correct is tensor([[8]])
pred is 24.183332920074463
correct is tensor([[3]])
pred is 30.918729305267334
correct is tensor([[4]])
pred is 20.307601988315582
correct is tensor([[7]])
pred is 75.52337050437927
correct is tensor([[0]])
pred is 24.444285035133362
correct is tensor([[1]])
pred is 20.307601988315582
correct is tensor([[3]])
pred is 25.373268127441406
correct is tensor([[3]])
pred is 23.230086266994476
correct is tensor([[8]])
pred is 24.326789379119873
correct is tensor([[6]])
pred is 20.307601988315582
correct is tensor([[1]])
pred is 20.307601988315582
correct is tensor([[8]])
pred is 24.51428771018982
correct is tensor([[1]])
pred is 20.307601988315582
correct is tensor([[6]])
pred is 20.307601988315582
correct is tensor([[4]])
pred is 20.307601988315582
correct is tensor([[6]])
pred is 20.307601988315582
28.691843782479946

In [189]:
# track test loss
test_loss = 0.0
class_correct = list(0. for i in range(9))
class_total = list(0. for i in range(9))
testing_target
model.eval()
# iterate over test data
for data, target in zip(testing_data, testing_target):
    # move tensors to GPU if CUDA is available

    # forward pass: compute predicted outputs by passing inputs to the model
    output = model(data.float())
    # calculate the batch loss
    loss = criterion(output, target.resize_(1))
    # update test loss 
    test_loss += loss.item()*data.size(0)
    # convert output probabilities to predicted class
    _, pred = torch.max(output, 1)    
    # compare predictions to true label
    correct_tensor = pred.eq(target.data.view_as(pred))
    correct = np.squeeze(correct_tensor.numpy()) 
    # calculate test accuracy for each object class
    for i in range(1):
        label = target.data[i]
        class_correct[label] += correct[i].item()
        class_total[label] += 1

# average test loss
test_loss = test_loss/len(test_loader.dataset)
print('Test Loss: {:.6f}\n'.format(test_loss))

for i in range(10):
    if class_total[i] > 0:
        print('Test Accuracy of %5s: %2d%% (%2d/%2d)' % (
            classes[i], 100 * class_correct[i] / class_total[i],
            np.sum(class_correct[i]), np.sum(class_total[i])))
    else:
        print('Test Accuracy of %5s: N/A (no training examples)' % (classes[i]))

print('\nTest Accuracy (Overall): %2d%% (%2d/%2d)' % (
    100. * np.sum(class_correct) / np.sum(class_total),
    np.sum(class_correct), np.sum(class_total)))

IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed